library(spdep)
library(maptools)
library(classInt)
library(RColorBrewer)
library(geoR)
library(leaflet)
stepD <- readShapePoly("/Volumes/CWILKASON/Zambia/Basemaps/StepD/StepD_StudyArea.shp")
clinics <- readShapePoints("/Volumes/CWILKASON/Zambia/Basemaps/Clinic.shp")
country <- readShapePoly("/Volumes/CWILKASON/Zambia/Zambia Shapes/country.shp")
